all:demo demo1 kehuduan111 fuwuduan111
demo:demo.cpp
	g++ -g -o demo demo.cpp -I/A/public /A/public/mpublic.cpp

demo1:demo1.cpp
	g++ -g -o demo1 demo1.cpp -I/A/public /A/public/mpublic.cpp

kehuduan111:kehuduan111.cpp
	g++ -g -o kehuduan111 kehuduan111.cpp -I/A/public /A/public/mpublic.cpp

fuwuduan111:fuwuduan111.cpp
	g++ -g -o fuwuduan111 fuwuduan111.cpp -I/A/public /A/public/mpublic.cpp

clean:
	rm -f demo demo1 kehuduan111 fuwuduan111